CREATE TABLE RESERVATION
(
    RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME     VARCHAR(255) NOT NULL,
    LAST_NAME      VARCHAR(255) NOT NULL,
    ROOM_NUMBER    SMALLINT     NOT NULL,
    START_DATE     DATE         NOT NULL,
    END_DATE       DATE         NOT NULL
);